---
- name: >
    RedHat | set_fact
      postfix_supported_os: True
  set_fact:
    postfix_supported_os: True

- name: install postfix
  yum: pkg="{{ item }}" state=installed
  with_items:
    - postfix
    - cyrus-sasl
    - cyrus-sasl-lib
    - cyrus-sasl-plain
